name: repo2docker
on: push

jobs:     
  repo2docker:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repo Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: login to docker
      run: |
        echo {{ secrets.PAT }} | docker login containers.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      env:
        REPO_TOKEN: ${{ secrets.PAT }}

    - name: test gcr 1
      run: |
        # build container with repo2docker
        docker pull alpine:3.10 
        docker tag alpine:3.10 containers.pkg.github.com/hamelsmu/repo2docker_test
        docker push containers.pkg.github.com/hamelsmu/repo2docker_test

    - name: test gcr 2
      run: |
        # build container with repo2docker
        pip install jupyter-repo2docker
        image_name_base="containers.pkg.github.com/$GITHUB_ACTOR/repo2docker"
        image_name_sha="$image_name_base:$GITHUB_SHA"
        image_name_latest="$image_name_base:latest"
        jupyter-repo2docker --no-run --image-name "$image_name_sha" .
        docker images
        # push container to the GitHub container registry
        docker tag $image_name_sha $image_name_latest
        echo "Built image: $image_name_sha"
        docker push $image_name_sha
        docker push $image_name_latest
