name: repo2docker
on: push

jobs:     
  repo2docker:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repo Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: login to docker
      run: |
        echo $REPO_TOKEN | docker login https://docker.pkg.github.com -u "github-actions[bot]" --password-stdin
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: build & push container
      run: |
        pip install jupyter-repo2docker
        image_name_base="containers.pkg.github.com/repo2docker"
        image_name_sha="$image_name_base:$GITHUB_SHA"
        image_name_latest="$image_name_base:latest"
        jupyter-repo2docker --no-run --debug --image-name "$image_name_sha" .
        docker tag $image_name_full "$image_name_base:latest"
        echo "Built image: $image_name_sha"
        docker push $image_name_sha
        docker push $image_name_latest
